### ISSUE TITLE
The dimension of feature is always (70,39) and don't changes with the actual speech length

### ISSUE THREAD

**Issue by FriedaSmith** [nijatmursali/NeuralNetworks#1]
Hello. I found The dimension of MFCC feature is always **(70,39)** and don't changes with the actual speech length. However,  The dimension of feature changes with the actual speech length, and the temporal information in the original speech is preserved by the  sequences between frames in the paper "**Speech Emotion Classification Using Attention-Based LSTM**".

**Comment by nijatmursali** [comment]
> Hello. I found The dimension of MFCC feature is always **(70,39)** and don't changes with the actual speech length. However, The dimension of feature changes with the actual speech length, and the temporal information in the original speech is preserved by the sequences between frames in the paper "**Speech Emotion Classification Using Attention-Based LSTM**".

Hello,

Yes, that one is solved. I will be pushing the updated code.
